baseURL = "https://decached.github.io/"
languageCode = "en-us"
title = "de-cached"
theme = "konoha"

[params]
    author = "Akash Kothawale"
    image = "/img/profile.jpeg"
    github = "decached"
    linkedin = "decached"
    twitter = "decached"
    stackoverflow = "users/1500692/akash-kothawale"
    email = "decached@gmail.com"
